import Foundation


enum Symptom: String, CaseIterable {
    case increasedIntracranialPressure = "Повышение внутричерепного давления"
    case skullEnlargement = "Увеличение объема черепа"
    case headache = "Головная боль"
    case dizziness = "Головокружение"
    case vomit = "Рвота"
    case hyposmia = "Гипосмия"
    case anosmia = "Аносмия"
    case hemianopia = "Гемианопсия"
    case flashingFliesBeforeTheEyes = "Мелькание мушек перед глазами"
    case eyeMovementRestrictions = "Ограничения движения глаза кнутри, вверх и вниз"
    case smoothingTheNasolabialFold = "Сглаживание носогубной складки"
    case asymmetryOfTheNasolabialFolds = "Асимметрия носогубных складок"
    case hearingLoss = "Снижение слуха"
    case imbalance = "Нарушение равновесия"
    case dysphagia = "Дисфагия"
    case dysphonia = "Дисфония"
    case dysarthria = "Дизартрия"
    case tongueDeviation = "Девиация языка"
    case motorAphasia = "Моторная афазия"
    case agraphia = "Аграфия"
    case frontalAtaxia = "Лобная атаксия"
    case anosognosia = "Анозогнозия"
    case alexia = "Алексия"
    case apraxia = "Апраксия"
    case acalculia = "Акалькулия"
    case sensoryAphasia = "Сенсорная афазия"
    case amnesticAphasia = "Амнестическая афазия"
    case olfactoryAgnosia = "Обонятельная агнозия"
    case auditoryAgnosia = "Слуховая агнозия"
    case auditoryHallucinations = "Слуховые галлюцинации"
    case visualAgnosia = "Зрительная агнозия"
    case photopsies = "Фотопсии"
    case epilepticSeizures = "Эпилептический припадки"
    case impairedCoordination = "Нарушение координации"
    case unsteadinessWhenWalking = "Шаткость при ходьбе"
}
